export interface Bussines {
    id:string,
    type_rif: String,
    rif: String,
    code_branch_office: String,
    comercial_designation: String,
    location: String,
    company_name: String,
    registration_date: String,
    duration: String,
    representative_legal: String,
    email_business: String,
    first_name_rl: String,
    last_name_rl:String,
    identity_card_rl:number,
    type_identity_card:string,
    position:number,
    email:string,
    tomo:number,
    folio:number,
    number:number,
    employer_number_ivss:number,
    web: string,
    phone:number,
    user_type_id:number,
    company_types_id:number,
    economic_activity_id:number,
    economic_sectors_id:number,
    state_id:number,
    country_id:number,
    municipality_id:number,
    parishe_id:number,
    owner_id:number
}